/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author laraashour
 */


import sa_orders.SA_ORD_API;
import customer.CustomerAPI_Impl;
import stock.CA_Stock_API_Impl;
import database.DBConnection;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.util.List;




public class Dashboard extends javax.swing.JPanel {
    
    private SA_ORD_API saOrdApi;
    private CustomerAPI_Impl customerApi;
    private CA_Stock_API_Impl stockApi;
    private Connection conn;
    
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        
        conn = DBConnection.getConnection();

        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Database connection failed.");
            return;
        }
        
        
        saOrdApi = new SA_ORD_API(conn);
        customerApi = new CustomerAPI_Impl();
        stockApi = new CA_Stock_API_Impl(conn);
        
        displayPendingOrders();
        loadStockTable();
        loadTodaysSales();
        loadActiveCustomers();
       
        
        
        
                       
    }
    
    
    private void displayPendingOrders(){
        int pendingCount = 0;
        
        try {
            
            
            

            java.sql.ResultSet rs = saOrdApi.getAllOrders();


            if (rs == null) return;

            while (rs.next()) {
                String status = rs.getString("status");

                if (status != null && status.equalsIgnoreCase("pending")) {
                    pendingCount++;
                }   
            }

        } catch (Exception e) {
                e.printStackTrace();
        }
        
        jPendingCount.setText(String.valueOf(pendingCount));
        
    }
    
    private void loadStockTable() {
        int totalStockItems = 0;

        if (stockApi == null) {
            return;
        }

        List<Object[]> items = stockApi.getAllStockItems();

        for (Object[] row : items) {
            totalStockItems++;
        }
        
        jStockItems.setText(String.valueOf(totalStockItems));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stockPanel1 = new javax.swing.JPanel();
        lbStock1 = new javax.swing.JLabel();
        jStockItems = new javax.swing.JLabel();
        salesPanel2 = new javax.swing.JPanel();
        lbSales2 = new javax.swing.JLabel();
        jSalesCount = new javax.swing.JLabel();
        pendingPanel4 = new javax.swing.JPanel();
        lbPending4 = new javax.swing.JLabel();
        jPendingCount = new javax.swing.JLabel();
        accountPanel3 = new javax.swing.JPanel();
        lbAccount3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        lbInfo1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        stockPanel1.setBackground(new java.awt.Color(255, 255, 255));
        stockPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbStock1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lbStock1.setText("Total Stock Items");

        jStockItems.setFont(new java.awt.Font("Helvetica Neue", 0, 100)); // NOI18N
        jStockItems.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jStockItems.setText("0");

        javax.swing.GroupLayout stockPanel1Layout = new javax.swing.GroupLayout(stockPanel1);
        stockPanel1.setLayout(stockPanel1Layout);
        stockPanel1Layout.setHorizontalGroup(
            stockPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(lbStock1)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(stockPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(stockPanel1Layout.createSequentialGroup()
                    .addGap(89, 89, 89)
                    .addComponent(jStockItems, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(128, Short.MAX_VALUE)))
        );
        stockPanel1Layout.setVerticalGroup(
            stockPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbStock1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(stockPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(stockPanel1Layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(jStockItems, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(47, Short.MAX_VALUE)))
        );

        salesPanel2.setBackground(new java.awt.Color(255, 255, 255));
        salesPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbSales2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lbSales2.setText("Today's Sales");

        jSalesCount.setFont(new java.awt.Font("Helvetica Neue", 0, 100)); // NOI18N
        jSalesCount.setText("0");

        javax.swing.GroupLayout salesPanel2Layout = new javax.swing.GroupLayout(salesPanel2);
        salesPanel2.setLayout(salesPanel2Layout);
        salesPanel2Layout.setHorizontalGroup(
            salesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesPanel2Layout.createSequentialGroup()
                .addGroup(salesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salesPanel2Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(lbSales2))
                    .addGroup(salesPanel2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jSalesCount)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        salesPanel2Layout.setVerticalGroup(
            salesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbSales2)
                .addGap(49, 49, 49)
                .addComponent(jSalesCount, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pendingPanel4.setBackground(new java.awt.Color(255, 255, 255));
        pendingPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbPending4.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lbPending4.setText("Pending Orders");

        jPendingCount.setFont(new java.awt.Font("Helvetica Neue", 0, 100)); // NOI18N
        jPendingCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPendingCount.setText("0");

        javax.swing.GroupLayout pendingPanel4Layout = new javax.swing.GroupLayout(pendingPanel4);
        pendingPanel4.setLayout(pendingPanel4Layout);
        pendingPanel4Layout.setHorizontalGroup(
            pendingPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendingPanel4Layout.createSequentialGroup()
                .addGroup(pendingPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pendingPanel4Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(lbPending4))
                    .addGroup(pendingPanel4Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jPendingCount, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        pendingPanel4Layout.setVerticalGroup(
            pendingPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendingPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbPending4)
                .addGap(26, 26, 26)
                .addComponent(jPendingCount, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        accountPanel3.setBackground(new java.awt.Color(255, 255, 255));
        accountPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbAccount3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lbAccount3.setText("Active Customers");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 100)); // NOI18N
        jLabel2.setText("0");

        javax.swing.GroupLayout accountPanel3Layout = new javax.swing.GroupLayout(accountPanel3);
        accountPanel3.setLayout(accountPanel3Layout);
        accountPanel3Layout.setHorizontalGroup(
            accountPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanel3Layout.createSequentialGroup()
                .addGroup(accountPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountPanel3Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(lbAccount3))
                    .addGroup(accountPanel3Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        accountPanel3Layout.setVerticalGroup(
            accountPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbAccount3)
                .addGap(49, 49, 49)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lbTitle.setText("Dashboard");

        lbInfo1.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        lbInfo1.setForeground(new java.awt.Color(102, 102, 102));
        lbInfo1.setText("Welcome to InfoPharma Ordering System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stockPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salesPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pendingPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accountPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbInfo1)
                    .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbInfo1)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pendingPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accountPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salesPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(123, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadTodaysSales() {
    double todaysSales = 0.0;

    try {
        java.sql.ResultSet rs = saOrdApi.getAllOrders();

        if (rs == null) {
            jSalesCount.setText("£0.00");
            return;
        }

        java.time.LocalDate today = java.time.LocalDate.now();

        while (rs.next()) {
            java.sql.Timestamp orderTimestamp = rs.getTimestamp("order_date");
            String status = rs.getString("status");
            double totalCost = rs.getDouble("total_cost");

            if (orderTimestamp != null) {
                java.time.LocalDate orderDate = orderTimestamp.toLocalDateTime().toLocalDate();

                if (today.equals(orderDate) && status != null && status.equalsIgnoreCase("Processed")) {
                    todaysSales += totalCost;
                }
            }
        }

    } catch (Exception e) {
        e.printStackTrace();
    }

    jSalesCount.setText(String.format("£%.2f", todaysSales));
}

private void loadActiveCustomers() {
    int activeCount = 0;

    try {
        List<customer.Customer> customers = customerApi.getAllCustomers();

        for (customer.Customer c : customers) {
            if (c != null
                    && c.getAccountStatus() != null
                    && c.getAccountStatus().equalsIgnoreCase("NORMAL")) {
                activeCount++;
            }
        }

    } catch (Exception e) {
        e.printStackTrace();
    }

    jLabel2.setText(String.valueOf(activeCount));
}
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountPanel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jPendingCount;
    private javax.swing.JLabel jSalesCount;
    private javax.swing.JLabel jStockItems;
    private javax.swing.JLabel lbAccount3;
    private javax.swing.JLabel lbInfo1;
    private javax.swing.JLabel lbPending4;
    private javax.swing.JLabel lbSales2;
    private javax.swing.JLabel lbStock1;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel pendingPanel4;
    private javax.swing.JPanel salesPanel2;
    private javax.swing.JPanel stockPanel1;
    // End of variables declaration//GEN-END:variables
}
