/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;


/**
 *
 * @author mehzanazkhan
 */

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import customer.CustomerAPI_Impl;
import java.util.LinkedHashMap;
import java.util.Map;
import login.SA_LOGIN_API;
import main.java.SA_COMMS_API_Impl;
import sa_orders.SA_ORD_API;
import java.sql.SQLException;
import java.sql.Connection;

//Initialises orders panel.
public class Orders extends javax.swing.JPanel {

    private static int orderCounter = 1;
    private SA_ORD_API saOrdApi;
    private SA_COMMS_API_Impl saCommsApi;
    private SA_LOGIN_API loginApi;
    private CustomerAPI_Impl customerApi;
    private String selectedMerchantUsername = "cosymed";
    private String selectedMerchantPassword = "bondstreet";

public Orders() {
    initComponents();

    //Creating API objects for the APIs needed
    saOrdApi = new SA_ORD_API(database.DBConnection.getConnection());
    saCommsApi = new SA_COMMS_API_Impl();
    loginApi = new SA_LOGIN_API();
    customerApi = new CustomerAPI_Impl();

    initialiseMerchantSelector();
    loginSelectedMerchantAndRefresh();

    //Key listener which allows the user to search for products in the catalogue
    jCatalogueSearchBar.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            searchCatalogue(jCatalogueSearchBar.getText());
        }
    });
}



        
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbInfo1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jOrdersTable = new javax.swing.JTable();
        lbInfo2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jCatalogueTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jCatalogueSearchBar = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        AccStatus = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnPlaceOrder = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        lbInfo1.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        lbInfo1.setForeground(new java.awt.Color(102, 102, 102));
        lbInfo1.setText("Welcome to the InfoPharma Ordering System");

        jTabbedPane2.setBackground(new java.awt.Color(239, 239, 239));

        jOrdersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Date", "Status", "Items", "Quantity", "Total cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jOrdersTable);
        if (jOrdersTable.getColumnModel().getColumnCount() > 0) {
            jOrdersTable.getColumnModel().getColumn(2).setHeaderValue("Status");
            jOrdersTable.getColumnModel().getColumn(3).setHeaderValue("Items");
            jOrdersTable.getColumnModel().getColumn(4).setHeaderValue("Quantity");
            jOrdersTable.getColumnModel().getColumn(5).setResizable(false);
            jOrdersTable.getColumnModel().getColumn(5).setHeaderValue("Total cost");
        }

        lbInfo2.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        lbInfo2.setForeground(new java.awt.Color(102, 102, 102));
        lbInfo2.setText("All your orders are displayed here:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbInfo2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("My Orders", jPanel3);

        jPanel4.setBackground(new java.awt.Color(239, 239, 239));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jCatalogueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jCatalogueTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setText("Search:");

        jCatalogueSearchBar.setText("Search by product name.....");
        jCatalogueSearchBar.addActionListener(this::jCatalogueSearchBarActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCatalogueSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCatalogueSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Product Catalogue", jPanel4);

        jPanel5.setBackground(new java.awt.Color(239, 239, 239));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel2.setText("Outstanding Balance:");

        jLabel3.setBackground(new java.awt.Color(239, 239, 239));
        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Account Balance", jPanel5);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setText("Orders to InfoPharma");

        AccStatus.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        AccStatus.setText("Normal");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel5.setText("Account Status:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(AccStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(AccStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("View order invoice");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        btnPlaceOrder.setBackground(new java.awt.Color(0, 0, 51));
        btnPlaceOrder.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnPlaceOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnPlaceOrder.setText("+ Place Order");
        btnPlaceOrder.addActionListener(this::btnPlaceOrderActionPerformed);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbInfo1))
                                .addGap(89, 89, 89)
                                .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jButton2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbInfo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(55, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
    }// </editor-fold>//GEN-END:initComponents


    //Method including a call to a backend method to retrieve all orders made to SA.
    private void loadOrders() {
        try {
            javax.swing.table.DefaultTableModel model =
                (javax.swing.table.DefaultTableModel) jOrdersTable.getModel();

            model.setRowCount(0); //table is emptied, no rows.
            
            //Backend method call to retireve all orders made to SA which are stored in the database.
            java.sql.ResultSet rs = saOrdApi.getAllOrders();

            //If no orders are retrieved then the system does nothing/nothing is displayed.
            if (rs == null) return;

            //For each order, retrieve and display the information in the table in Orders panel.
            while (rs.next()) {
                String orderId = rs.getString("order_ref");
                String status = rs.getString("status"); //retrieves status of order
                int productId = rs.getInt("product_id"); //retrieves product id in order
                int quantity = rs.getInt("quantity"); //retrieves quantity
                java.sql.Timestamp orderTimestamp = rs.getTimestamp("order_date"); //retieves date

                String date = orderTimestamp == null
                    ? "-"
                    : new java.text.SimpleDateFormat("dd/MM/yyyy").format(orderTimestamp); //retrieves date in correct format.
                
                
                double totalCost = rs.getDouble("total_cost"); //retrieves total cost

                //Displays information from the order specified by the order ID in rows.
                model.addRow(new Object[]{
                    orderId,
                    date,
                    status,
                    productId,
                    quantity,
                    totalCost
                });
            }

        } catch (Exception e) {
                e.printStackTrace();
        }
    }

    //Changes made to the orders are updated on the GUI, new orders, and status changes.
    public void refreshOrders() {
        loadOrders();
        refreshStatusesFromSA();
    }
    
    //Changes made to the balance, like when an transactio is completed, it will display.
    public void refreshBalance() {
        loadLoggedInBalance();
    }
    
    
//Method including a call to a backend method to retrieve all orders made to SA.
private void loadCatalogue() {
    try {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jCatalogueTable.getModel();
        model.setRowCount(0); //table is emptied, no rows.

        //Retrieves catalogue from SA Comms API based on merchant
        String jsonResponse = saCommsApi.getActiveCatalogue("username=" + selectedMerchantUsername);
        System.out.println("RAW catalogue response: " + jsonResponse);

        //Code that handles if the catalogue wasn't retrieved from SA, displays messge to user
        if (jsonResponse == null || jsonResponse.isBlank()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "No catalogue data returned from SA.");
            return;
        }

        
        Map<Integer, String> catalogueItems = parseCatalogueResponse(jsonResponse);
        System.out.println("Parsed catalogue size: " + catalogueItems.size());

        //For each catalogue item mapping a new row is added including the product and it's information
            for (Map.Entry<Integer, String> item : catalogueItems.entrySet()) {
                model.addRow(new Object[]{item.getKey(), item.getValue()});
            }

            //Exception handling for if the above code causes an error and catalogue isn't retrieved, message displayed to user
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                "Failed to load SA catalogue: " + e.getMessage());
        }
    }
    
    
//Allows user to search catalogue by product name
private void searchCatalogue(String searchText) {
    try {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jCatalogueTable.getModel();
        model.setRowCount(0);

        //Retrieves catalogue from SA Comms API based on merchant
        String jsonResponse = saCommsApi.getActiveCatalogue("username=" + selectedMerchantUsername);

        //Code that handles if the catalogue wasn't retrieved from SA, system does nothing
        if (jsonResponse == null || jsonResponse.isBlank()) {
            return;
        }

        Map<Integer, String> catalogueItems = parseCatalogueResponse(jsonResponse);

        String search = searchText == null ? "" : searchText.trim().toLowerCase();

        //For each catalogue item mapping a new row is added including the product and it's information
        for (Map.Entry<Integer, String> item : catalogueItems.entrySet()) {
            String productName = item.getValue() == null ? "" : item.getValue().toLowerCase();

            //product row is displayed depending on if what the user typed matches a products name.
            if (search.isBlank() || productName.contains(search)) {
                model.addRow(new Object[]{item.getKey(), item.getValue()});
            }
        }

        //If there is an error in the above code this exception handles it
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    //code for loading the balance depending on the merchant
private void loadLoggedInBalance() {
    try {
        
        //Calls backend method from SA COMMS API to retrieve the balance based on the merchant
        String response = saCommsApi.getBalance("username=" + selectedMerchantUsername);
        System.out.println("SA balance response: " + response);

        //If no balance is retrieved then the displayed balance is £0.00
        if (response == null || response.isBlank()) {
            jLabel3.setText("£0.00");
            return;
        }

        double balance = Double.parseDouble(response.trim());
        jLabel3.setText(String.format("£%.2f", balance)); //ensures the balanc eis displayed int he correct format

        //If there is an issue with the above code (with retrieving the balance) then displayed balance is £0.00yu8i
    } catch (Exception e) {
        jLabel3.setText("£0.00");
        e.printStackTrace();
    }
}
    

    //Adds a row to the order table
    public void addOrderRow(Object[] row){
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jOrdersTable.getModel();
        model.addRow(row);
    }
                                         

    private void jCatalogueSearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCatalogueSearchBarActionPerformed
        String text = jCatalogueSearchBar.getText();
        searchCatalogue(text);
    }//GEN-LAST:event_jCatalogueSearchBarActionPerformed

    
//This button is for viewing the order invoice
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    int selectedRow = jOrdersTable.getSelectedRow();

    //A row from the orders table must be selected to view it's invoice
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Please select an order to view the invoice of.");
        return;
    }

    String orderId = jOrdersTable.getValueAt(selectedRow, 0).toString(); //retrieves order id

    try {
        System.out.println("=== INVOICE REQUEST DEBUG ===");
        System.out.println("Selected row: " + selectedRow);
        System.out.println("Order ID from table (column 0): [" + orderId + "]");
        System.out.println("Order ID length: " + orderId.length());
        System.out.println("Order ID type/format: appears to be " +
            (orderId.matches("\\d{5}-\\d{2}-\\d{2}") ? "NUMERIC (like 22026-04-12)" : "OTHER"));

        //Calls backend method from SA COMMS API to retrieve the Invoice based on the order ID.
        String response = saCommsApi.getInvoice("orderId=" + orderId);
        System.out.println("SA invoice response for " + orderId + ": " + response);

        //If no invoice data is retrieved then a message is displayed
        if (response == null || response.isBlank()) {
            showInvoiceFallback(orderId, "No invoice data returned from SA.");
            return;
        }

        if (response.toLowerCase().contains("couldnt")
            || response.toLowerCase().contains("couldn't")
            || response.toLowerCase().contains("could not")
            || response.toLowerCase().contains("invoice details")) {
            showInvoiceFallback(orderId, response);
            return;
        }

        //The following block of code displays the invoice.
        String formattedInvoice = formatInvoiceResponse(response);

        javax.swing.JTextArea area = new javax.swing.JTextArea(formattedInvoice);
        area.setEditable(false);
        area.setLineWrap(true);
        area.setWrapStyleWord(true);
        area.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 13));

        javax.swing.JScrollPane pane = new javax.swing.JScrollPane(area);
        pane.setPreferredSize(new java.awt.Dimension(520, 340));

        javax.swing.JOptionPane.showMessageDialog(
            this,
            pane,
            "Order Invoice",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        //if there is an error in the above code to retrieve and display the invoice then a message is displayed.
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this,
            "Failed to load invoice from SA.");
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    //This is the button for placing an order.
    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
    System.out.println("btnPlaceOrder clicked, AccStatus = '" + AccStatus.getText() + "'");
    
    //Order can only be placed if the account status is normal.
    if (AccStatus.getText().equals("Normal")){
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);

        //Displays a dialog pane/window to add items to the created order and to submit it.
        NewOrder dialog;
        if (parentWindow instanceof java.awt.Frame) {
            dialog = new NewOrder((java.awt.Frame) parentWindow, true, this);
        } else {
            dialog = new NewOrder(null, true, this);
        }

        dialog.setLocationRelativeTo(parentWindow);
        dialog.setVisible(true);

        // Reload from DB after modal closes so newly submitted orders are shown.
        refreshOrders();
    } else {
        //If account status is not normal, a message is shown that the user cannot place an order.
        javax.swing.JOptionPane.showMessageDialog(this,
                "Account status must be normal to place an order.");
    
    }
        
    

    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        //If via the combo box a merchant is selected then system logs in with the specified merchant
        if (saCommsApi != null) {
            loginSelectedMerchantAndRefresh();
        }    
    }//GEN-LAST:event_jComboBox1ActionPerformed

//Converts a JSON catalogue response into an ordered map of product IDs to their corresponding descriptions
private Map<Integer, String> parseCatalogueResponse(String jsonResponse) {
    Map<Integer, String> result = new LinkedHashMap<>();

    try {
        ObjectMapper mapper = new ObjectMapper();
        JsonNode root = mapper.readTree(jsonResponse);

        JsonNode itemIds = root.get("item_id");
        JsonNode descriptions = root.get("description");

        if (itemIds != null && descriptions != null && itemIds.isArray() && descriptions.isArray()) {
            int count = Math.min(itemIds.size(), descriptions.size());

            for (int i = 0; i < count; i++) {
                int productId = itemIds.get(i).asInt();
                String productName = descriptions.get(i).asText();

                result.put(productId, productName);
            }
        }

        //If the above code as an error then it is handles with the bellow code
    } catch (Exception e) {
        e.printStackTrace();
    }

    return result;
}

//Displays alternative if Invoice cannot be retrieved from SA
private void showInvoiceFallback(String orderId, String failureReason) {
    Map<String, Integer> orderItems = saOrdApi.viewOrder(orderId);
    StringBuilder invoice = new StringBuilder();

    invoice.append("SA invoice not available for order: ").append(orderId).append("\n");
    invoice.append("Failure reason: ").append(failureReason).append("\n\n");
    invoice.append("Local order details below:\n");
    invoice.append("---------------------------\n");

    if (orderItems.isEmpty()) {
        invoice.append("No local order items found for this order.\n");
    } else {
        invoice.append(String.format("%-40s %10s\n", "Product", "Quantity"));
        invoice.append("------------------------------------------------\n");
        for (Map.Entry<String, Integer> item : orderItems.entrySet()) {
            invoice.append(String.format("%-40s %10d\n", item.getKey(), item.getValue()));
        }
    }

    invoice.append("\n");
    invoice.append("Note: This is a local order summary because SA invoice details could not be retrieved.\n");
    invoice.append("If some products are missing or quantities differ, please verify the order in SA and retry.\n");

    javax.swing.JTextArea area = new javax.swing.JTextArea(invoice.toString());
    area.setEditable(false);
    area.setLineWrap(true);
    area.setWrapStyleWord(true);
    area.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 13));

    javax.swing.JScrollPane pane = new javax.swing.JScrollPane(area);
    pane.setPreferredSize(new java.awt.Dimension(500, 320));

    javax.swing.JOptionPane.showMessageDialog(
        this,
        pane,
        "Order Summary - Invoice Unavailable",
        javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
}

//Returns/converts key as an integer
private int extractInt(JsonNode node, String... keys) {
    for (String key : keys) {
        if (node.has(key) && !node.get(key).isNull()) {
            try {
                return node.get(key).asInt();
            } catch (Exception ignored) {
            }
        }
    }
    return 0;
}

//Returns/converts key as an string
private String extractString(JsonNode node, String... keys) {
    for (String key : keys) {
        if (node.has(key) && !node.get(key).isNull()) {
            try {
                return node.get(key).asText();
            } catch (Exception ignored) {
            }
        }
    }
    return "";
}

//Status of orders are retrieved from SA to ensure they are updated.
private void refreshStatusesFromSA() {
    try {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jOrdersTable.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {
            String orderId = String.valueOf(model.getValueAt(i, 0));

            if (orderId == null || orderId.isBlank()) {
                continue;
            }

            if (!orderId.startsWith("220")) {
                continue;
            }

            String response = saCommsApi.getOrderStatuses("orderId=" + orderId);
            System.out.println("SA status response for " + orderId + ": " + response);

            if (response == null || response.isBlank() || response.equals("ORDER_NOT_FOUND")) {
                continue;
            }

            String status = parseOrderStatusResponse(response);
            if (!status.isBlank()) {
                model.setValueAt(status, i, 2);

                String localStatus = saOrdApi.getLocalOrderStatus(orderId);
                System.out.println("Local status for " + orderId + ": " + localStatus);

                if (status.equalsIgnoreCase("delivered")
                        && !"delivered".equalsIgnoreCase(localStatus)) {
                    recordDeliveredOrderLocally(orderId);
                }
            }
        }

        //If above code causes an error, it is handled below
    } catch (Exception e) {
        e.printStackTrace();
    }
}



//Parses a JSON response to extract and return the orderStatus value as a string, 
private String parseOrderStatusResponse(String jsonResponse) {
    try {
        ObjectMapper mapper = new ObjectMapper();
        JsonNode root = mapper.readTree(jsonResponse);

        //Returns an empty string if it’s missing or an error occurs.
        if (root.has("orderStatus") && !root.get("orderStatus").isNull()) {
            return root.get("orderStatus").asText();
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    return "";
}

private void recordDeliveredOrderLocally(String orderId) {
    
    //A connection (to DB) is initialised
    Connection conn = null;

    try {
        System.out.println("recordDeliveredOrderLocally called for order: " + orderId);

        //Retrieve database connection
        conn = database.DBConnection.getConnection();
        conn.setAutoCommit(false);

        //Initialises order and stock APIs
        sa_orders.SA_ORD_API localOrdApi = new sa_orders.SA_ORD_API(conn);
        stock.CA_Stock_API_Impl stockApi = new stock.CA_Stock_API_Impl(conn);

        //Retrieves current status of order
        String localStatus = localOrdApi.getLocalOrderStatus(orderId);
        System.out.println("Local status before update: " + localStatus);

        //If already delivered, system does nothing.
        if ("delivered".equalsIgnoreCase(localStatus)) {
            System.out.println("Order already marked delivered locally, skipping.");
            conn.rollback();
            return;
        }

        //Items in the order are all retrieved
        Map<Integer, Integer> items = localOrdApi.getOrderItems(orderId);
        System.out.println("Items found for order: " + items);

        //If there are no items in the order then system does nothing
        if (items == null || items.isEmpty()) {
            System.out.println("No local items found for order: " + orderId);
            conn.rollback();
            return;
        }

        //Update stock for each product/item
        for (Map.Entry<Integer, Integer> entry : items.entrySet()) {
            int productId = entry.getKey();
            int quantity = entry.getValue();

            System.out.println("Updating stock for product " + productId + " by " + quantity);

            //Stock updated according to delivery
            boolean stockUpdated = stockApi.recordDelivery(productId, quantity, null);
            
            //If the stock is not updated then stock update has failed
            if (!stockUpdated) {
                throw new SQLException("Failed to update stock for product " + productId);
            }
        }

        //Order status updated to delivered
        boolean statusUpdated = localOrdApi.updateOrderStatus(orderId, "delivered");
        
        //If the order status is not updated then status update has failed
        if (!statusUpdated) {
            throw new SQLException("Failed to update local order status for " + orderId);
        }

        conn.commit();
        System.out.println("Delivery recorded locally for order: " + orderId);

        //If transaction fails then this is handled
    } catch (Exception e) {
        try {
            if (conn != null) {
                conn.rollback();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        e.printStackTrace();

    } finally {
        try {
            if (conn != null) {
                conn.setAutoCommit(true);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}

//Formats the invoice/insure that it is displayed properly
private String formatInvoiceResponse(String jsonResponse) {
    try {
        ObjectMapper mapper = new ObjectMapper();
        JsonNode root = mapper.readTree(jsonResponse);

        StringBuilder invoice = new StringBuilder();

        invoice.append("INVOICE\n");
        invoice.append("========================================\n");
        invoice.append("Invoice ID: ").append(extractString(root, "invoice_id")).append("\n");
        invoice.append("Order Date: ").append(extractString(root, "order_date")).append("\n");
        invoice.append("Client: ").append(extractString(root, "client")).append("\n");
        invoice.append("Address: ").append(extractString(root, "address")).append("\n");
        invoice.append("Postcode: ").append(extractString(root, "postcode")).append("\n");
        invoice.append("Phone: ").append(extractString(root, "phone")).append("\n");
        invoice.append("Email: ").append(extractString(root, "email")).append("\n");
        invoice.append("Company Reg No: ").append(extractString(root, "company_reg_num")).append("\n");
        invoice.append("\n");

        double totalWithoutDiscount = root.has("total_without_discount") ? root.get("total_without_discount").asDouble() : 0.0;
        double totalWithDiscount = root.has("total_with_discount") ? root.get("total_with_discount").asDouble() : 0.0;
        double amountStillDue = root.has("amount_still_due") ? root.get("amount_still_due").asDouble() : 0.0;

        invoice.append("Items\n");
        invoice.append("----------------------------------------\n");

        JsonNode items = root.get("items");
        JsonNode quantities = root.get("quantity");
        JsonNode itemCosts = root.get("items_cost");
        JsonNode units = root.get("units");
        JsonNode prices = root.get("prices");

        if (items != null && items.isArray() && quantities != null && quantities.isArray()) {
            for (int i = 0; i < items.size(); i++) {
                String itemName = items.get(i).asText();
                int qty = i < quantities.size() ? quantities.get(i).asInt() : 0;
                int unitCount = (units != null && i < units.size()) ? units.get(i).asInt() : 0;
                double unitPrice = (prices != null && i < prices.size()) ? prices.get(i).asDouble() : 0.0;
                double lineCost = (itemCosts != null && i < itemCosts.size()) ? itemCosts.get(i).asDouble() : 0.0;

                invoice.append(itemName).append("\n");
                invoice.append("  Quantity ordered: ").append(qty).append("\n");
                invoice.append("  Units per pack: ").append(unitCount).append("\n");
                invoice.append("  Price per item: £").append(String.format("%.2f", unitPrice)).append("\n");
                invoice.append("  Line total: £").append(String.format("%.2f", lineCost)).append("\n\n");
            }
        } else {
            invoice.append("No item details available.\n\n");
        }

        invoice.append("========================================\n");
        invoice.append("Total before discount: £").append(String.format("%.2f", totalWithoutDiscount)).append("\n");
        invoice.append("Total after discount:  £").append(String.format("%.2f", totalWithDiscount)).append("\n");
        invoice.append("Amount still due:      £").append(String.format("%.2f", amountStillDue)).append("\n");

        return invoice.toString();

        //Handles errors in the code above
    } catch (Exception e) {
        e.printStackTrace();
        return jsonResponse;
    }
}

//Combobox used to select the merchant is initialised/options are added
private void initialiseMerchantSelector() {
    jComboBox1.removeAllItems();
    jComboBox1.addItem("Cosymed Ltd");
    jComboBox1.addItem("CityPharmacy");
    jComboBox1.addItem("HelloPharmacy");

    jComboBox1.setSelectedItem("Cosymed Ltd");
}

//Merchant logged in based on the users selection on the combobox
private void loginSelectedMerchantAndRefresh() {
    try {
        String selected = String.valueOf(jComboBox1.getSelectedItem());

        if ("CityPharmacy".equals(selected)) {
            selectedMerchantUsername = "city";
            selectedMerchantPassword = "northampton";
        } else if ("HelloPharmacy".equals(selected)) {
            selectedMerchantUsername = "hello";
            selectedMerchantPassword = "there";
        } else {
            selectedMerchantUsername = "cosymed";
            selectedMerchantPassword = "bondstreet";
        }

        //Retrieves loggin details on the merchant logged in
        boolean loggedIn = saCommsApi.login(selectedMerchantUsername, selectedMerchantPassword);
        System.out.println("SA login result for " + selectedMerchantUsername + ": " + loggedIn);

        if (!loggedIn) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Failed to log in to IPOS-SA for " + selected);
            return;
        }

        //loads in orders, statuses from SA, catalogue and the balance of logged in user
        loadOrders();
        refreshStatusesFromSA();
        loadCatalogue();
        loadLoggedInBalance();

        //If above code causes an error this is handled below
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this,
            "Failed to switch merchant.");
    }
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccStatus;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jCatalogueSearchBar;
    private javax.swing.JTable jCatalogueTable;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTable jOrdersTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lbInfo1;
    private javax.swing.JLabel lbInfo2;
    // End of variables declaration//GEN-END:variables
}
